name: Build and Deploy docs
on:
  pull_request:
    branches:
      - 'master'
      - 'main'
  push:
    branches:
      - 'master'
      - 'main'
    tags: '*'

defaults:
  run:
    shell: bash

jobs:

  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      #- name: apt-get update
      #  run: sudo apt-get update
        
      #- name: install latex
      #  run: sudo apt-get install texlive-luatex latexmk texlive-latex-extra

      - name: Set up Julia packages
        run: pip install -U pip
      
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      
      - name: Generate docs
        run: bash run.sh
        
      - name: Deploy to gh-pages

        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: sphinx/build/html
